# Generated by Django 5.1 on 2024-09-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_productconfiguration_purchase_product_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="product_configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce.productconfiguration",
            ),
        ),
    ]
